id: P78E9F482
initial_creation_type: input
source_metadata:
  title: Fourteenth Dalai Lama Series
  language: de
  description: 'Texts by and about His Holiness the 14th Dalai Lama, Tenzin Gyatso
    (bstan ''dzin rgya mtsho, b. 1935):'
  volume:
    20dfbdf8435143c28a079abbdbaa3e52:
      title: Aspiration Prayer for the Flourishing of the Jonang Teachings
      parent: Aspiration Prayers
    7ecf949de63e488e8ff1807528a7ac9f:
      title: The Prayer of the Words of Truth
      parent: Aspiration Prayers
    39e5936f261d48818a200b1951edcd6a:
      title: 'The Resounding Drum of Truth: A Prayer and Aspiration'
      parent: Aspiration Prayers
    7a9be26cc21b4a1a8cb165197f6e51db:
      title: 'The Sage''s Harmonious Song of Truth: A Prayer for the Flourishing of
        the Non-Sectarian Teachings of the Buddha'
      parent: Aspiration Prayers
    1b00331f919f4e629ebaf80d0398b514:
      title: 'The Song of Devotion: Verses of Aspiration for the Fulfilment of the
        Enlightened Vision of Khenchen Jigme Phuntsok, the Reincarnation of Terton
        Lerab Lingpa'
      parent: Aspiration Prayers
    f03a43811a2544f3bccb17f8176137c0:
      title: A Yearning Song of Prayer to Invoke the Wisdom Mind of the Compassionate
        Teacher Padmasambhava
      parent: Guru Rinpoche Prayers
    ecc62c7aa53a4758849b136e83b620f2:
      title: A Letter to the Fourteenth Dalai Lama, Supreme Victorious Guru of the
        Beings of the Three Realms
      parent: Letters
    ffe8b07c46a64f8bacc115df9c2ea7a8:
      title: A Prayer to Kindle the Three Faiths, Addressed to the Seventeen Great
        Paṇḍitas of Glorious Nālandā
      parent: Lineage Prayers
    302ada1dc54440b49b62d390993663cb:
      title: 'The Swift Infusion of Blessings: A Lineage Prayer for the Single Mind
        Kīla Heart-Practice, Part of the ''Neck Pouch Dagger’ (Purba Gulkhukma) Cycle'
      parent: Lineage Prayers
    d863ed89ce6a4078b585bbca116170a0:
      title: 'Granting the Wish for Immortality: A Prayer for the Long Life of Dzarong
        Trulshik Rinpoche, the Representative of Guru Rinpoche'
      parent: Long Life Prayers
    9091bf4c259b480cbf57fa347316c6da:
      title: Long Life Prayer for Kyabje Dzarong Trulshik Rinpoche
      parent: Long Life Prayers
    3a8b7bc68d4842d5942cc4f6fa7ae8bc:
      title: Prayer for the Long Life of Dzogchen Rinpoche
      parent: Long Life Prayers
    7109135603ae499ab1a45ff5709735fb:
      title: Prayer for the Long Life of His Holiness the Dalai Lama
      parent: Long Life Prayers
    1e5a9d77e2414e14bd14b199a23742ba:
      title: Prayer for the Long Life of His Holiness the Fourteenth Dalai Lama
      parent: Long Life Prayers
    987690b079d04a5399c978a91c4266c4:
      title: 'The Great Treasure of a Hundred Blessings: A Prayer for the Long Life
        of Ḍākinī Muntso Rinpoche'
      parent: Long Life Prayers
    a586aedfd3554b5997da7db8ba5feb80:
      title: 'The Magical Wish-Fulfilling Tree: A Prayer for the Long Life of His
        Holiness the Dalai Lama'
      parent: Long Life Prayers
    32a375a9151b4611abed082a8a65d3c5:
      title: 'The Melody of The Nectar of Immortality: A Prayer for the Long Life
        of His Holiness the Fourteenth Dalai Lama, Supreme Victor and Omniscient One
        by Jamyang Khyentse Chökyi Lodrö'
      parent: Long Life Prayers
    f06829f1b1b3440bbdf833278026dfae:
      title: 'The Music of Immortality: A Prayer for the Long Life of His Holiness
        the Dalai Lama'
      parent: Long Life Prayers
    83ab23ac0b164eb9a3cfff77526d55f3:
      title: A Homage to His Holiness the Dalai Lama
      parent: Praise
    0d917d7b162e41d8b9be2d33df461e32:
      title: Verses of Homage
      parent: Praise
    d1c01e76901c47168a21d3f284593a56:
      title: Prayer for the Fulfilment of Aspirations
      parent: Prayers
    178551947e06467ba121bd8cb08fc60e:
      title: Prayer to His Holiness the Dalai Lama
      parent: Prayers
    927d5682fdfd49fcb73793e7af481fff:
      title: Prayer for the Swift Rebirth of Kyabjé Trulshik Rinpoche
      parent: Swift Rebirth Prayers
    a7df2f6cd9664fe4beebd96d305c7442:
      title: 'Bestowing the Splendour of All That is Desirable: Fire Offering for
        the ''Neck-Pouch Dagger’ (Purba Gulkhukma) Cycle'
      parent: Vajrakīla
created_at: '2022-02-28T23:17:49.858336'
last_modified_at: '2022-02-28T23:17:49.858339'
